#!/bin/bash
# Claude Code SessionStart フック
# gh CLI を未インストールなら自動セットアップする。
#
# 認証は 1Password の `GitHub PAT (Template)` item から PAT を取得し、
# `~/.gh-env` に `export GH_TOKEN=...` として書き出す（既存の ~/.grok-env パターンと整合）。
# gh は GH_TOKEN env var を見ると `gh auth login` 不要で動作する。
#
# 用途:
# - Web 実行環境（remote sandbox）で `scripts/sync-derived-repos.sh` や
#   `gh secret set` 等の cross-repo 操作を可能にする
# - GitHub MCP 経由では届かない gh 専用機能（org secrets / workflow run 等）
#
# 利用側スクリプトは先頭で `[ -f "$HOME/.gh-env" ] && . "$HOME/.gh-env"` を実行する。

set -u

log() { printf '[gh-setup] %s\n' "$*" >&2; }

GH_CLI_VERSION="${GH_CLI_VERSION:-2.62.0}"
SETUP_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/claude-template-setup"
GH_MARKER="$SETUP_CACHE_DIR/gh-${GH_CLI_VERSION}.ok"
mkdir -p "$SETUP_CACHE_DIR" 2>/dev/null || true

gh_install() {
  local ARCH GH_ARCH TMPDIR_GH URL INSTALL_DIR
  ARCH="$(uname -m)"
  case "$ARCH" in
    x86_64|amd64) GH_ARCH="amd64" ;;
    aarch64|arm64) GH_ARCH="arm64" ;;
    *)
      log "未対応アーキテクチャ ($ARCH)。gh CLI を手動で入れてください。"
      return 1
      ;;
  esac

  TMPDIR_GH="$(mktemp -d)"
  URL="https://github.com/cli/cli/releases/download/v${GH_CLI_VERSION}/gh_${GH_CLI_VERSION}_linux_${GH_ARCH}.tar.gz"

  if curl -fsSL "$URL" -o "$TMPDIR_GH/gh.tar.gz" 2>/tmp/gh-install.log && \
     tar -xzf "$TMPDIR_GH/gh.tar.gz" -C "$TMPDIR_GH" 2>>/tmp/gh-install.log; then
    INSTALL_DIR="${GH_INSTALL_DIR:-$HOME/.local/bin}"
    mkdir -p "$INSTALL_DIR"
    install -m 0755 "$TMPDIR_GH/gh_${GH_CLI_VERSION}_linux_${GH_ARCH}/bin/gh" "$INSTALL_DIR/gh"
    case ":$PATH:" in
      *":$INSTALL_DIR:"*) ;;
      *) export PATH="$INSTALL_DIR:$PATH" ;;
    esac
    log "gh CLI インストール完了: $($INSTALL_DIR/gh --version 2>/dev/null | head -1 || echo unknown) ($INSTALL_DIR)"
    log "PATH に $INSTALL_DIR を恒久追加することを推奨"
    touch "$GH_MARKER" 2>/dev/null || true
    rm -rf "$TMPDIR_GH"
    return 0
  else
    log "gh CLI インストール失敗。/tmp/gh-install.log を確認。"
    rm -rf "$TMPDIR_GH"
    return 1
  fi
}

# キャッシュマーカーが gh 実体と整合していれば version 起動を省略する。
gh_marker_valid() {
  [ -f "$GH_MARKER" ] || return 1
  local bin
  bin="$(command -v gh 2>/dev/null)" || return 1
  [ -e "$bin" ] || return 1
  [ "$bin" -nt "$GH_MARKER" ] && return 1
  return 0
}

if ! command -v gh >/dev/null 2>&1; then
  log "gh CLI 未検出。v${GH_CLI_VERSION} をインストールします。"
  gh_install || true
elif gh_marker_valid; then
  log "gh CLI 確認: v${GH_CLI_VERSION} (cached)"
else
  CURRENT_VERSION="$(gh --version 2>/dev/null | head -1 | awk '{print $3}' || echo unknown)"
  if [ "$CURRENT_VERSION" = "$GH_CLI_VERSION" ]; then
    log "gh CLI 確認: v${CURRENT_VERSION} (一致)"
    touch "$GH_MARKER" 2>/dev/null || true
  else
    log "gh CLI バージョン不一致 (現在: v${CURRENT_VERSION} / 期待: v${GH_CLI_VERSION})。既存を維持します。"
    log "       強制再インストールするには cache marker を削除: rm $GH_MARKER"
  fi
fi

# --- 認証情報の persist ---
if ! command -v gh >/dev/null 2>&1; then
  exit 0
fi

GH_ENV="$HOME/.gh-env"

# 既に有効な GH_TOKEN が ~/.gh-env にある場合は再取得しない
if [ -f "$GH_ENV" ] && grep -q "^export GH_TOKEN=" "$GH_ENV" 2>/dev/null; then
  log "認証: $GH_ENV 既存（再取得スキップ）"
  exit 0
fi

if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ] || ! command -v op >/dev/null 2>&1; then
  log "認証: 未認証 (OP_SERVICE_ACCOUNT_TOKEN 未設定 or op CLI 不在)"
  log "       手動で $GH_ENV に 'export GH_TOKEN=ghp_...' を書き込むか、gh auth login してください"
  exit 0
fi

log "認証: 1Password から PAT 取得を試行..."

# 1Password の GitHub PAT (Template) は履歴的事情で credential field が 2 つあり
# default 側が空、custom 側（id `e5sajszvymiflbwtwihuksfjz4` 等）に実値が入っている
# パターンが存在する。--fields credential では空を引きやすいため、jq で
# 「label が credential かつ非空の field」を全走査して最初の値を採用する。
# (learnings/insights.md 2026-05-04「op default 空 field に引きずられる罠」参照)
PAT=""
if command -v jq >/dev/null 2>&1; then
  PAT="$(op item get 'GitHub PAT (Template)' --vault claude-code-secrets --format=json --reveal 2>/dev/null \
    | jq -r '.fields[] | select(.label == "credential" and (.value // "") != "") | .value' 2>/dev/null \
    | head -n 1)"
fi

# jq 未導入リポ向けフォールバック
if [ -z "$PAT" ]; then
  PAT="$(op item get 'GitHub PAT (Template)' --vault claude-code-secrets --fields credential --reveal 2>/dev/null)"
fi

if [ -z "$PAT" ]; then
  log "警告: 1Password から PAT 取得失敗。手動で 'gh auth login' を実行してください。"
  log "       hint: 'GitHub PAT (Template)' item の credential field が空の可能性"
  exit 0
fi

# ~/.gh-env に export GH_TOKEN を書き出し（既存 ~/.grok-env と整合する pattern）
umask 077
{
  echo "# Generated by .claude/hooks/session-start-gh-setup.sh (do not commit)"
  echo "export GH_TOKEN='$PAT'"
} > "$GH_ENV"
chmod 600 "$GH_ENV"
log "認証: $GH_ENV に GH_TOKEN を書き出し (40 char ghp_ PAT)"

# ~/.bashrc に idempotent に source 行追加（インタラクティブシェル向け）
BASHRC="$HOME/.bashrc"
touch "$BASHRC"
if ! grep -qF ".gh-env" "$BASHRC" 2>/dev/null; then
  echo "[ -f \"\$HOME/.gh-env\" ] && . \"\$HOME/.gh-env\"" >> "$BASHRC"
fi

log "ヒント: 非対話シェル（bash -c）からは source されないため、gh を使う"
log "       スクリプトは先頭で '[ -f \"\$HOME/.gh-env\" ] && . \"\$HOME/.gh-env\"' を実行する"

exit 0
