#!/bin/bash
# setup-op.sh — SessionStart hook: 1Password CLI + secret bootstrap
#
# OP_SERVICE_ACCOUNT_TOKEN が env に注入されていれば、op CLI を install して
# vault から各 API キーを fetch し、~/.search-api-env / ~/.<domain>-env に persist する。
# ~/.bashrc も idempotent に wire する。
#
# 2026-05-16 確認：Web sandbox の egress allowlist が緩和され、
# cache.agilebits.com / api.1password.com 両方が通る。
#
# 失敗時は silent no-op（次の hook やセッション進行をブロックしない）。
#
# ----------------------------------------------------------------------
# 🔧 リポジトリ適応時のカスタマイズポイント
# ----------------------------------------------------------------------
# 1. VAULT 名を自分の 1Password vault に変更（既定: claude-code-secrets）
# 2. op_field の item 名を実 vault に存在するものに変更
# 3. domain-specific な env file 出力ブロック（"# >>> CUSTOM DOMAIN" 以下）を
#    用途に合わせて追加・削除する
# 4. ~/.bashrc に追加する env file リスト（最下行ループ）を同期
# ----------------------------------------------------------------------

set -u

if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]; then
  exit 0
fi

# op CLI bootstrap（不在なら install）
OP_BIN=""
if command -v op >/dev/null 2>&1; then
  OP_BIN="op"
else
  OP_VERSION="2.30.3"
  TMPDIR_OP=$(mktemp -d)
  if curl -fsSL --max-time 30 -o "$TMPDIR_OP/op.zip" \
       "https://cache.agilebits.com/dist/1P/op2/pkg/v${OP_VERSION}/op_linux_amd64_v${OP_VERSION}.zip" 2>/dev/null; then
    unzip -q -o "$TMPDIR_OP/op.zip" -d "$TMPDIR_OP" 2>/dev/null || true
    if [ -x "$TMPDIR_OP/op" ]; then
      if install -m 0755 "$TMPDIR_OP/op" /usr/local/bin/op 2>/dev/null; then
        OP_BIN="/usr/local/bin/op"
      else
        mkdir -p "$HOME/.local/bin"
        install -m 0755 "$TMPDIR_OP/op" "$HOME/.local/bin/op"
        OP_BIN="$HOME/.local/bin/op"
      fi
    fi
  fi
  rm -rf "$TMPDIR_OP"
fi

[ -n "$OP_BIN" ] || exit 0
"$OP_BIN" whoami >/dev/null 2>&1 || exit 0

# ----------------------------------------------------------------------
# CUSTOMIZE: vault 名（既定は claude-code-secrets / 自分の vault 名に変更可）
# ----------------------------------------------------------------------
VAULT="claude-code-secrets"

# op item get wrapper — 非ASCIIフィールド名（"認証情報"）は op read だと
# "invalid character in secret reference" で蹴られるので item get + --fields を使う。
# 失敗時は空文字を返す（silent）。
op_field() {
  local item="$1" field="$2"
  "$OP_BIN" item get "$item" --vault "$VAULT" --fields "label=$field" --reveal 2>/dev/null || true
}

# ----------------------------------------------------------------------
# 汎用 API keys（どのリポでも便利・残しておくのを推奨）
# ----------------------------------------------------------------------
BRAVE_KEY=$(op_field "Brave Search API Key" "認証情報")
CSE_KEY=$(op_field "Google CSE API Key" "認証情報")
CSE_ID=$(op_field "Google CSE ID" "認証情報")
XAI_KEY=$(op_field "Grok API Key (Template)" "credential")

# ----------------------------------------------------------------------
# >>> CUSTOM DOMAIN: ドメイン固有の API keys（自分の用途に合わせて追加・削除）
#
# 例（参考・必要に応じてコメント解除して差し替え）:
#   MAPS_KEY=$(op_field "Maps API Key (My Project)" "認証情報")          # Google Maps
#   STRIPE_KEY=$(op_field "Stripe API Key" "credential")                # 決済
#   AIRTABLE_KEY=$(op_field "Airtable API Key" "credential")            # データ管理
#   NOTION_KEY=$(op_field "Notion API Key" "credential")                # ナレッジ
#   PLAID_KEYS=$(op_field "Plaid Sandbox" "credential")                 # 金融データ
#
# 削除する場合：このブロックを丸ごと削除して下の "# <<< CUSTOM DOMAIN" まで消す
# ----------------------------------------------------------------------
# <<< CUSTOM DOMAIN

umask 077

# ~/.search-api-env: Brave + Google CSE（汎用検索）
SEARCH_ENV="$HOME/.search-api-env"
{
  echo "# Generated by .claude/scripts/setup-op.sh (do not commit)"
  [ -n "$BRAVE_KEY" ] && echo "export BRAVE_API_KEY='$BRAVE_KEY'"
  [ -n "$CSE_KEY" ]   && echo "export GOOGLE_CSE_KEY='$CSE_KEY'"
  [ -n "$CSE_ID" ]    && echo "export GOOGLE_CSE_ID='$CSE_ID'"
} > "$SEARCH_ENV"
chmod 600 "$SEARCH_ENV"

# ~/.grok-env: xAI Grok（汎用 LLM 二次オピニオン）
GROK_ENV="$HOME/.grok-env"
{
  echo "# Generated by .claude/scripts/setup-op.sh (do not commit)"
  [ -n "$XAI_KEY" ] && echo "export XAI_API_KEY='$XAI_KEY'"
} > "$GROK_ENV"
chmod 600 "$GROK_ENV"

# ----------------------------------------------------------------------
# >>> CUSTOM DOMAIN: ドメイン固有の env file 出力
#
# 例（参考・上の op_field と対で追加）:
#   MAPS_ENV="$HOME/.maps-env"
#   {
#     echo "# Generated by setup-op.sh"
#     [ -n "$MAPS_KEY" ] && echo "export MAPS_API_KEY='$MAPS_KEY'"
#   } > "$MAPS_ENV"
#   chmod 600 "$MAPS_ENV"
# ----------------------------------------------------------------------
# <<< CUSTOM DOMAIN

# ~/.bashrc に idempotent に source 行を追加
# CUSTOMIZE: ドメイン固有の env file を追加した場合、下の for ループにも追加
BASHRC="$HOME/.bashrc"
touch "$BASHRC"
for F in .search-api-env .grok-env; do
  if ! grep -qF "$F" "$BASHRC" 2>/dev/null; then
    echo "[ -f \"\$HOME/$F\" ] && . \"\$HOME/$F\"" >> "$BASHRC"
  fi
done

exit 0
