#!/bin/bash
# gen-env-ref.sh — secrets.map から「op:// ID 参照テンプレート」を生成する（非 secret 出力）
#
# 単一の真実源 1Password vault "claude-code-secrets" を前提に、
# 人間が書いた論理名→item title マップを、安定して解決できる **item ID 参照** へ変換する。
# 出力は op:// 参照だけで **解決済み secret 値は一切含まない**（ディスクに平文 secret を残さない）。
#
# 使い方:
#   bash scripts/gen-env-ref.sh                         # ci/secrets/secrets.map → stdout
#   bash scripts/gen-env-ref.sh --map path/to.map       # 別マップ
#   bash scripts/gen-env-ref.sh --strict                # field 空/欠落も fail（既定は warn+skip）
#   VAULT=other-vault bash scripts/gen-env-ref.sh        # vault 上書き
#
# 想定運用: 生成物を `op run --env-file=<生成物> -- <cmd>` に渡す（ファイルレス注入）。
#           `op inject -o .env` でのファイル化は **しない**（残存リスクのため）。
#
# 終了コード: 0=全解決 / 1=エラー（title 未解決・曖昧一致・--strict での空 field 等）
#
# R7 準拠: title に括弧があっても op item get なら解決可。得た ID で op:// を組む。

set -uo pipefail

MAP="ci/secrets/secrets.map"
STRICT=""
VAULT="${VAULT:-claude-code-secrets}"

while [ $# -gt 0 ]; do
  case "$1" in
    --map) MAP="${2:?--map にパス}"; shift 2 ;;
    --strict) STRICT=1; shift ;;
    -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "不明な引数: $1" >&2; exit 1 ;;
  esac
done

[ -f "$MAP" ] || { echo "ERROR: マップが見つかりません: $MAP" >&2; exit 1; }
command -v op >/dev/null 2>&1 || { echo "ERROR: op CLI 未インストール" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq 未インストール" >&2; exit 1; }
op whoami >/dev/null 2>&1 || { echo "ERROR: op 未認証（OP_SERVICE_ACCOUNT_TOKEN を確認）" >&2; exit 1; }

trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; s="${s%"${s##*[![:space:]]}"}"; printf '%s' "$s"; }

echo "# generated by gen-env-ref.sh — op:// ID 参照のみ（secret 値は含まない / do not commit）"
echo "# vault=$VAULT  source=$MAP"

errors=0
seen_names=""
while IFS='|' read -r raw_name raw_title raw_field; do
  # コメント・空行スキップ
  case "$(trim "${raw_name:-}")" in ''|\#*) continue ;; esac
  name="$(trim "$raw_name")"; title="$(trim "${raw_title:-}")"; field="$(trim "${raw_field:-}")"
  [ -n "$title" ] && [ -n "$field" ] || { echo "ERROR: 不正な行（name=$name title='$title' field='$field'）" >&2; errors=$((errors+1)); continue; }

  # 論理名の重複検出
  case " $seen_names " in *" $name "*) echo "ERROR: 論理名が重複: $name" >&2; errors=$((errors+1)); continue ;; esac
  seen_names="$seen_names $name"

  # title → item JSON 解決（曖昧一致・未存在は op が非0で返る）
  if ! item_json="$(op item get "$title" --vault "$VAULT" --format json 2>/tmp/gen-env-ref.err)"; then
    echo "ERROR: item 解決失敗（title='$title'）: $(head -1 /tmp/gen-env-ref.err)" >&2
    errors=$((errors+1)); continue
  fi
  id="$(printf '%s' "$item_json" | jq -r '.id // empty')"
  [ -n "$id" ] || { echo "ERROR: ID 取得不可（title='$title'）" >&2; errors=$((errors+1)); continue; }

  # field の存在＆値有無を確認（値そのものは取得しない＝メタのみ）。
  # op の op:// 参照は field を id でも label でも解決するため、両方で照合する
  # （例: Grok item はキーが id=ランダム・label="credential" のフィールドに入っている）。
  has_value="$(printf '%s' "$item_json" | jq -r --arg f "$field" '[.fields[]? | select(.id==$f or .label==$f) | (.value!=null and .value!="")] | any')"
  if [ "$has_value" != "true" ]; then
    if [ -n "$STRICT" ]; then
      echo "ERROR: field 未投入: $name ($title/$field)" >&2; errors=$((errors+1)); continue
    else
      echo "# SKIP ${name}: field '${field}' が空/欠落（title=${title}）— vault にキー未登録" >&2
      echo "# SKIP $name=op://$VAULT/$id/$field  (field empty)"
      continue
    fi
  fi

  printf '%s=op://%s/%s/%s\n' "$name" "$VAULT" "$id" "$field"
done < "$MAP"
rm -f /tmp/gen-env-ref.err

if [ "$errors" -gt 0 ]; then
  echo "ERROR: $errors 件の解決失敗" >&2
  exit 1
fi
